# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.2
	minecraft_version=26.2
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency = >=26.2 <26.3
	malilib_dependency = >=0.29.4
	minihud_conflict = <0.34.3
	tweakeroo_conflict = <0.23.1

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions = 26.2

# Dependencies
	fabric_api_version=0.152.1+26.2

	# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib/
	# https://jitpack.io/#sakura-ryoko/malilib
	# https://github.com/sakura-ryoko/malilib/releases
	malilib_version = fi.dy.masa.malilib:malilib-fabric-26.2:0.29.4

	# https://jitpack.io/#sakura-ryoko/tweakeroo
	# https://github.com/sakura-ryoko/tweakeroo/releases
	tweakeroo_version = fi.dy.masa.tweakeroo:tweakeroo-fabric-26.2:0.29.3

	# https://jitpack.io/#sakura-ryoko/itemscroller
	# https://github.com/sakura-ryoko/itemscroller/releases
	itemscroller_version = fi.dy.masa.itemscroller:itemscroller-fabric-26.2:0.32.1

	# https://jitpack.io/#sakura-ryoko/litematica
	# https://github.com/sakura-ryoko/litematica/releases
	litematica_version = fi.dy.masa.litematica:litematica-fabric-26.2:0.28.5

	# https://jitpack.io/#sakura-ryoko/minihud
	# https://github.com/sakura-ryoko/minihud/releases
	minihud_version = fi.dy.masa.minihud:minihud-fabric-26.2:0.40.5

	# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/
	mod_menu_version = 20.0.0-beta.2
